include(GNUInstallDirs)

install(TARGETS kiseki RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Runtime)
if(WIN32)
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION ${CMAKE_INSTALL_BINDIR})
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_COMPONENT Runtime)
    include(InstallRequiredSystemLibraries)
    if(TARGET kiseki_ibinputsimulator)
        install(FILES "${KISEKI_IBINPUTSIMULATOR_DLL}" DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Runtime)
        install(FILES "${KISEKI_IBINPUTSIMULATOR_SOURCE}/LICENSE.txt"
            DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/licenses RENAME IbInputSimulator.txt COMPONENT Runtime)
    endif()
endif()

install(DIRECTORY skills/ DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/skills COMPONENT Runtime
    PATTERN "__pycache__" EXCLUDE PATTERN "*.pyc" EXCLUDE)
install(DIRECTORY docs/ DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/docs COMPONENT Runtime)
install(FILES README.md AGENTS.md DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki COMPONENT Runtime)
install(FILES docs/install.html DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki COMPONENT Runtime)
install(FILES "${cli11_SOURCE_DIR}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/licenses RENAME CLI11.txt COMPONENT Runtime)
install(FILES "${nlohmann_json_SOURCE_DIR}/LICENSE.MIT" DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/licenses RENAME nlohmann-json.txt COMPONENT Runtime)
install(FILES "${cpp_httplib_SOURCE_DIR}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/kiseki/licenses RENAME cpp-httplib.txt COMPONENT Runtime)

set(CPACK_PACKAGE_NAME "KisekiInput")
set(CPACK_PACKAGE_VENDOR "Kiseki Input")
set(CPACK_PACKAGE_CONTACT "https://github.com/win10ogod/kiseki-input/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native desktop operation CLI for agents")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/win10ogod/kiseki-input")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Kiseki Input")
set(CPACK_PACKAGE_FILE_NAME "KisekiInput-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_COMPONENTS_ALL Runtime)
set(CPACK_MONOLITHIC_INSTALL ON)
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/docs/install.html")

if(WIN32)
    set(CPACK_GENERATOR "NSIS;ZIP")
    set(CPACK_NSIS_DISPLAY_NAME "Kiseki Input")
    set(CPACK_NSIS_PACKAGE_NAME "Kiseki Input")
    set(CPACK_NSIS_MODIFY_PATH ON)
    set(CPACK_NSIS_IGNORE_LICENSE_PAGE ON)
    set(CPACK_NSIS_HELP_LINK "https://github.com/win10ogod/kiseki-input/blob/master/docs/install.md")
    set(CPACK_NSIS_URL_INFO_ABOUT "${CPACK_PACKAGE_HOMEPAGE_URL}")
    set(CPACK_NSIS_MENU_LINKS "share/kiseki/install.html" "Start here - Installation and CUA setup")
    set(CPACK_NSIS_WELCOME_TITLE "Install Kiseki Input")
    set(CPACK_NSIS_FINISH_TITLE "Open a new terminal to use Kiseki")
elseif(APPLE)
    set(CPACK_GENERATOR "productbuild;TGZ")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
    set(CPACK_PRODUCTBUILD_IDENTIFIER "io.github.win10ogod.kiseki-input")
    set(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_SOURCE_DIR}/docs/install.html")
else()
    set(CPACK_GENERATOR "DEB;TGZ")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
    set(CPACK_DEBIAN_PACKAGE_NAME "kiseki-input")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Kiseki Input contributors")
    set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "curl, xdg-desktop-portal, xdg-desktop-portal-gtk")
endif()

include(CPack)
